enum SCREENS {
  // STACKS
  AUTH_STACK = 'SCREEN:AUTH_STACK',
  BOTTOM_BAR = 'SCREEN:BOTTOM_BAR',

  // SCREENS
  SIGN_IN = 'SCREEN:SIGN_IN',
  HOME = 'SCREEN:HOME',
  ONBOARDING_SCREEN = 'SCREEN:ONBOARDING_SCREEN',
  PROFILE_SCREEN = 'SCREEN:PROFILE_SCREEN',
}

export default SCREENS;
